# Action and state space columns used in all harvesting phases

phases:
  phase_1_approach:
    - tof_cols
    - inhand_cam_feature_cols
    # - joint_states_cols.pos
    # - ee_pose_cols
    - apple_position_groundtruth
    - action_cols

  phase_2_contact:
    - tof_cols
    - air_pressure_cols
    - wrench_cols
    # - joint_states_cols.pos
    # - ee_pose_cols
    - apple_position_groundtruth
    - action_cols

  phase_3_pick:
    - tof_cols
    - air_pressure_cols
    - wrench_cols
    # - joint_states_cols.pos
    # - ee_pose_cols
    - apple_position_groundtruth
    - action_cols

  phase_4_disposal:
    - tof_cols
    - air_pressure_cols
    - wrench_cols
    # - joint_states_cols.pos
    # - ee_pose_cols
    - action_cols


action_cols_at_base_frame:

  # Velocities @ base frame
  - v_eef_x
  - v_eef_y
  - v_eef_z
  - w_eef_x
  - w_eef_y
  - w_eef_z

action_cols:
  # These are the actions used for training the model
  # Velocities
  # - v_eef._x._eef_frame
  # - v_eef._y._eef_frame
  # - v_eef._z._eef_frame
  # - w_eef._x._eef_frame
  # - w_eef._y._eef_frame
  # - w_eef._z._eef_frame

  # Deltas @ ee frame
  - Δ_lin_eef._x._eef_frame
  - Δ_lin_eef._y._eef_frame
  - Δ_lin_eef._z._eef_frame
  - Δ_ori_eef._x._eef_frame
  - Δ_ori_eef._y._eef_frame
  - Δ_ori_eef._z._eef_frame

apple_position_groundtruth:
  # - 'apple._x._base'
  # - 'apple._y._base'
  # - 'apple._z._base'
  - 'apple._x._ee'
  - 'apple._y._ee'
  - 'apple._z._ee'


air_pressure_cols:
  - scA
  - scB
  - scC

tof_cols:
  - tof

wrench_cols:
  - _wrench._force._x
  - _wrench._force._y
  - _wrench._force._z
  - _wrench._torque._x
  - _wrench._torque._y
  - _wrench._torque._z

ee_pose_cols:
  - _pose._position._x
  - _pose._position._y
  - _pose._position._z
  - _pose._orientation._x
  - _pose._orientation._y
  - _pose._orientation._z
  - _pose._orientation._w

joint_states_cols:
  pos:
    - pos_joint_1
    - pos_joint_2
    - pos_joint_3
    - pos_joint_4
    - pos_joint_5
    - pos_joint_6
    - pos_joint_7
  vel:
    - vel_joint_1
    - vel_joint_2
    - vel_joint_3
    - vel_joint_4
    - vel_joint_5
    - vel_joint_6
    - vel_joint_7
  eff:
    - eff_joint_1
    - eff_joint_2
    - eff_joint_3
    - eff_joint_4
    - eff_joint_5
    - eff_joint_6
    - eff_joint_7

inhand_cam_feature_cols:
  prefix: "f"
  count: 64        # Number of features extracted from in-hand camera images, Layer 15 of Segmentation Network
  # - f11
  # - f21
  # - f52
  # - f23
  # - f4
  # - f14
  # - f60
  # - f41 
  # - f19
  # - f10
  # - f54
  # - f34
  # - f15
  # - f6
  # - f55
  # - f30
  # - f45

